notifications:
  email: false

language: generic

sudo: false

cache:
  directories:
    - $HOME/miniconda3

before_cache:
  - rm -rf $HOME/miniconda3/pkgs/cache
  - rm -rf $HOME/miniconda3/envs/hosts

os:
  - linux
  - osx

env:
  - PYTHON_VERSION="3.5"

before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"

install:
  - ci/install_conda.sh
  - ./install_stable.sh
  - zipline ingest
  - alphatools ingest